# Generated by Django 6.0.2 on 2026-02-24 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('discount_percent', models.PositiveIntegerField()),
                ('expire_date', models.DateTimeField()),
                ('max_usage', models.PositiveIntegerField()),
                ('used_count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
