# Generated by Django 6.0.2 on 2026-02-25 11:37

import apps.users.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_address_user_remove_user_email_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apps.users.managers.CustomUserManager()),
            ],
        ),
        migrations.RenameField(
            model_name='address',
            old_name='street',
            new_name='address_line',
        ),
        migrations.RemoveField(
            model_name='address',
            name='apartment',
        ),
        migrations.RemoveField(
            model_name='address',
            name='entrance',
        ),
        migrations.RemoveField(
            model_name='address',
            name='floor',
        ),
        migrations.RemoveField(
            model_name='address',
            name='house',
        ),
        migrations.RemoveField(
            model_name='address',
            name='intercom',
        ),
        migrations.AddField(
            model_name='address',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
