# Generated by Django 6.0.2 on 2026-02-25 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='profile',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='addresses',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='users.address'),
        ),
    ]
