# Generated by Django 6.0.2 on 2026-03-12 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_is_active_product_updated_at_and_more'),
        ('users', '0003_favorite'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(fields=('user', 'product'), name='to check user have unique product in favorite', violation_error_message='You already added this product to favorites.'),
        ),
    ]
