# Generated by Django 6.0.2 on 2026-02-25 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_address_profile_userprofile_addresses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birth_date',
            field=models.DateField(default='2000-01-01'),
        ),
    ]
